# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InspectionApp' do
    
    pod 'YYText'
    pod 'YYModel'
    pod 'SwipeView'
    pod 'YYCategories'
    pod 'AMap2DMap'
    pod 'AMapLocation'
    pod 'AMapSearch'
    pod 'JPush'
    pod 'SDWebImage'
    pod 'AgoraRtcEngine_iOS', '~> 2.4.0.1'

end
